#!/bin/bash
#location of "Analysis" folder
cd /home/schul105/depot/Tau3Mu/analysis/2024/CMSSW_14_0_18/src/Analysis
cmsenv
#compile
#g++ -I $ROOTSYS/include Analysis_chunk*.cpp `root-config --glibs` `root-config --libs` `root-config --cflags`  -L $ROOTSYS/lib -o executable*
sleep 1

#execute
#./executable "data_control" "2017F"


#please note that "compile" and "execute" are placeholders and should not be removed
